---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: metal-lb
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: metal-lb
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metallb
    version: 0.9.7
  values:
    configInline:
      address-pools:
      - addresses:
        - 10.10.1.230-10.10.1.250
        name: default
        protocol: layer2
